version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "81:81"
      - "443:443"  
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5001:5000"
    env_file: .env
    restart: always

  backend:
    build: ./backend
    ports:
      - "8000:8000" 
    env_file: .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kanokari
      POSTGRES_USER: user
      POSTGRES_PASSWORD: tralalelotralala123098
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
